# Generated by Django 3.1.4 on 2020-12-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0009_auto_20201230_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.asset')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.protocol')),
            ],
        ),
    ]
