# Generated by Django 3.1.4 on 2021-01-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0011_auto_20201231_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={},
        ),
        migrations.AlterModelOptions(
            name='macm',
            options={},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='macm',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='macm',
            new_name='app',
        ),
    ]
