# Generated by Django 3.1.4 on 2021-01-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0012_auto_20210102_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
