# Generated by Django 3.1.4 on 2021-01-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0013_relation_relation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='asset_type',
        ),
        migrations.DeleteModel(
            name='Asset_type',
        ),
    ]
