# Generated by Django 3.1.4 on 2021-01-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0014_auto_20210105_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Attribute_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Threat_Attribute_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_scenario', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='threat_attribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='threat_attribute',
            name='threat',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='attribute_value',
            name='acronym',
        ),
        migrations.AddField(
            model_name='attribute_value',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.attribute'),
        ),
        migrations.DeleteModel(
            name='Asset_Attribute',
        ),
        migrations.DeleteModel(
            name='Threat_Attribute',
        ),
        migrations.AddField(
            model_name='threat_attribute_value',
            name='attribute_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.attribute_value'),
        ),
        migrations.AddField(
            model_name='threat_attribute_value',
            name='threat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threat'),
        ),
        migrations.AddField(
            model_name='asset_attribute_value',
            name='attribute_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.attribute_value'),
        ),
    ]
