# Generated by Django 3.1.4 on 2021-03-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0015_auto_20210105_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threat_attribute_value',
            old_name='threat_scenario',
            new_name='behavior',
        ),
    ]
