# Generated by Django 3.1.4 on 2021-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0016_auto_20210304_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='cia',
            field=models.CharField(choices=[('Confidentiality', 'Confidentiality'), ('Integrity', 'Integrity'), ('Availability', 'Availability')], max_length=500, null=True),
        ),
    ]
