# Generated by Django 3.1.4 on 2021-03-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0017_threat_cia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threat',
            old_name='cia',
            new_name='security_requirement',
        ),
    ]
