# Generated by Django 3.1.4 on 2021-03-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0018_auto_20210311_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='threat',
            name='security_requirement',
        ),
        migrations.CreateModel(
            name='Threat_CIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.cia')),
                ('stride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.stride')),
            ],
        ),
    ]
