# Generated by Django 3.1.4 on 2021-03-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0019_auto_20210315_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat_cia',
            name='stride',
        ),
        migrations.AddField(
            model_name='threat_cia',
            name='threat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threat'),
        ),
        migrations.AlterField(
            model_name='threat_cia',
            name='cia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.cia'),
        ),
    ]
