# Generated by Django 3.1.4 on 2020-12-28 19:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Asset_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.asset_type')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controls',
            },
        ),
        migrations.CreateModel(
            name='MACM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('macm', models.FileField(upload_to='systems/macm/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cypher', 'macm'])])),
            ],
            options={
                'verbose_name': 'MACM',
                'verbose_name_plural': 'MACMs',
            },
        ),
        migrations.CreateModel(
            name='Stride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('owasp_ease_of_discovery', models.IntegerField()),
                ('owasp_ease_of_exploit', models.IntegerField()),
                ('owasp_intrusion_detection', models.IntegerField()),
                ('owasp_awareness', models.IntegerField()),
                ('owasp_loss_of_confidentiality', models.IntegerField()),
                ('owasp_loss_of_integrity', models.IntegerField()),
                ('owasp_loss_of_availability', models.IntegerField()),
                ('owasp_loss_of_accountability', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Threat',
                'verbose_name_plural': 'Threats',
            },
        ),
        migrations.CreateModel(
            name='Threat_Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.control')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Threat_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.attribute')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Subthreat_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=100)),
                ('sub_threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subthreat', to='SlaGenerator.threat')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat', to='SlaGenerator.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Subcontrol_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=100)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='SlaGenerator.control')),
                ('sub_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontrol', to='SlaGenerator.control')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.attribute_value'),
        ),
        migrations.CreateModel(
            name='Asset_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.asset_type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='macm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.macm'),
        ),
    ]
