# Generated by Django 3.1.4 on 2020-12-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='asset_type',
            options={},
        ),
        migrations.AlterModelOptions(
            name='threat',
            options={},
        ),
        migrations.AddField(
            model_name='asset_type',
            name='acronym',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset_type',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='threat_family',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='source',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Threat_Stride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.stride')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Threat_Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.protocol')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threat')),
            ],
        ),
    ]
