# Generated by Django 3.1.4 on 2020-12-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0002_auto_20201228_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='owasp_awareness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='owasp_ease_of_discovery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='owasp_ease_of_exploit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='owasp_intrusion_detection',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='owasp_loss_of_accountability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='owasp_loss_of_availability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='owasp_loss_of_confidentiality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='owasp_loss_of_integrity',
            field=models.IntegerField(null=True),
        ),
    ]
