# Generated by Django 3.1.4 on 2020-12-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0003_auto_20201228_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_value',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_value',
            name='attribute_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
