# Generated by Django 3.1.4 on 2020-12-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0004_auto_20201229_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_value',
            name='acronym',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
