# Generated by Django 3.1.4 on 2020-12-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0006_auto_20201229_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat_attribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.attribute'),
        ),
        migrations.AlterField(
            model_name='threat_attribute',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.threat'),
        ),
    ]
