# Generated by Django 3.1.4 on 2020-12-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0008_control_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macm',
            old_name='name',
            new_name='application',
        ),
        migrations.RemoveField(
            model_name='macm',
            name='macm',
        ),
        migrations.AddField(
            model_name='macm',
            name='appId',
            field=models.IntegerField(null=True),
        ),
    ]
