# Generated by Django 3.1.4 on 2020-12-31 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SlaGenerator', '0010_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='macm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.macm'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.asset'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SlaGenerator.protocol'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
